In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [2]:
df=pd.read_csv("mail_data.csv")

In [3]:
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
df.isna().sum()

Category    0
Message     0
dtype: int64

In [5]:
maildata=df.where((pd.notnull(df)),"")

In [6]:
df.columns

Index(['Category', 'Message'], dtype='object')

In [7]:
maildata.loc[maildata['Category']=="spam",'Category']=0

In [8]:
maildata.loc[maildata['Category']=="ham",'Category']=1

In [9]:
maildata

Category                                            Message
0           1  Go until jurong point, crazy.. Available only ...
1           1                      Ok lar... Joking wif u oni...
2           0  Free entry in 2 a wkly comp to win FA Cup fina...
3           1  U dun say so early hor... U c already then say...
4           1  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567        0  This is the 2nd time we have tried 2 contact u...
5568        1               Will ü b going to esplanade fr home?
5569        1  Pity, * was in mood for that. So...any other s...
5570        1  The guy did some bitching but I acted like i'd...
5571        1                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [10]:
df.columns

Index(['Category', 'Message'], dtype='object')

In [11]:
maildata['Message']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [12]:
X=maildata['Message']
Y=maildata['Category']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.20,random_state=42)

In [14]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(4457,) (1115,) (4457,) (1115,)


In [15]:
feature_extraction=TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

In [16]:
x_trainf=feature_extraction.fit_transform(x_train)
x_testf=feature_extraction.transform(x_test)

In [17]:
y_train=y_train.astype(int)
y_test=y_test.astype(int)

In [18]:
model=LogisticRegression()
model.fit(x_trainf,y_train)

LogisticRegression()

In [19]:
pred=model.predict(x_trainf)

In [20]:
pred

array([0, 1, 1, ..., 1, 1, 1])

In [21]:
pred=model.predict(x_testf)

In [22]:
acc=accuracy_score(y_test,pred)

In [23]:
acc

0.967713004484305

In [24]:
input_ma=['Ive been searching for the right word']
maill=feature_extraction.transform(input_ma)
model.predict(maill)


array([1])

In [25]:
inn=["this 2nd time to contact you, you won money..hurry up click link here"]
maill=feature_extraction.transform(inn)
model.predict(maill)

array([1])